# This is a basic workflow to help you get started with Actions

name: Create tag, release & release notes

on:   
  workflow_run:
    workflows: [Trigger]
    types: [completed]
    branches: [main]
  workflow_dispatch:
    inputs:
      commit:
        default: ''
        type: string
        required: false
        description: The short sha (8 first characters) of the commit to deploy, leave empty to deploy the latest commit.


jobs:
  create-release:
    with:
      environment: 'prod'
    permissions: write-all
    name: 'Create Release'
    runs-on: 'ubuntu-latest'
    if: github.ref == 'refs/heads/main'
    steps:
      - name: set date env
        run: echo "NOW=$(date +'v%Y.%m.%d%H%M%S')" >> $GITHUB_ENV
      - name: Create release notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEST: ${{ GITHUB.SHA }}
          TEST2: "$GITHUB_SHA"
        run: |
          gh release create "${{ env.NOW }}" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${{ env.NOW }}" \
              --target=${{ github.sha }}
